### ISSUE TITLE
Layout Wrappers and Containers

### ISSUE THREAD

**Issue by AccessiT3ch** [aschall777/booki77#5]
@aschall777 

Currently it looks like there are a lot of elements that are direct children of the `<body>` tag, which is technically ok, but can make consistent spacing a little difficult. A lot of times it can be really helpful to wrap elements in additional containers (divs, sections, etc), much like you've done with your `<header>` and `<section>` tag.

- [ ] Apply Consistent Spacing
- [ ] Wrap Accommodations and Most Popular sections together

## Consistent Spacing
Such wrappers can be really helpful for applying styling via a single selector, rather than reapplying the styling to every element.

```HTML
<body>
    <header>...</header>
    <section id="search">...</section>
    <section id="accommodations">...</section>
    <section id="popular">...</section>
    <section id="activities">...</section>
    <footer>...</footer>
</body>
```
In the case above, a few CSS rules can be written to apply uniform spacing:
```CSS
header, section, footer {
    margin: 1rem 2rem;  /* remember these should be fixed units! */
}
header {
    margin-top: 0; /* we don't want a top margin on our header */
}
footer {
   margin-bottom: 0; /* we don't want a bottom margin on our footer */
}
```

## High Level Layout
Another reason to wrap elements in containers is specifically for layout purposes! For example, the sections for Accommodations and Most Popular need to be on the same row, so all we need to do is wrap both sections in another container:

```HTML
<body>
    <header>...</header>
    <section id="search">...</section>

    <div class="container"> 
        <section id="accommodations">...</section>
        <section id="popular">...</section>
    </div>

    <section id="activities">...</section>
    <footer>...</footer>
</body>
```
In this case, `div.container` can be styled as a simple flexbox/grid layout with only two items to lay out. (I'm choosing to use a `div` as a wrapper because I just need a generic box to apply some styling to, which is essentially for what `div`s were originally intended!)
