### ISSUE TITLE
Activities Section Layout

### ISSUE THREAD

**Issue by AccessiT3ch** [aschall777/booki77#8]
Use Flexbox or Grid (with `grid-area` names) to layout cards in the actives section.

### With Flexbox
The tricky thing with this design is the combination of stacked and non-stacked cards in the same view, there are a few potential ways to do this but perhaps the easiest will be to wrap the stacked cards in a container. In this approach, only the tall cards and the "stack" wrapper will act as flex children.

```HTML
<div class="flex-container">

    <article class="activity-card"> (tall card) </article>

    <div class="stack">
         <article class="activity-card"> (short card) </article>
         <article class="activity-card"> (short card) </article>
    </div>

    <article class="activity-card"> (tall card) </article>

    <div class="stack">
         <article class="activity-card"> (short card) </article>
         <article class="activity-card"> (short card) </article>
    </div>

</div>
```

### With Grid
It looks like this design could be pretty quickly implemented with a grid layout using `grid-area` styling on the card. ([See W3's example to see how it works!](https://www.w3schools.com/css/tryit.asp?filename=trycss_grid_layout_named)) In this approach, each card would have a unique class or id which would be used to style the `grid-area` property. If our HTML looked like this:
```HTML
<div class="grid-container">
    <article class="activity-card one"> (tall card) </article>
     <article class="activity-card two"> (short card) </article>
     <article class="activity-card three"> (short card) </article>
     <article class="activity-card four"> (tall card) </article>
     <article class="activity-card five"> (short card) </article>
     <article class="activity-card six"> (short card) </article>
</div>
```
Then your visual styling for the cards can be under a `.activity-card { ... }` style block, and your grid layout styling could look like:

```CSS
.activity-card.one { grid-name: 'one' }
.activity-card.two { grid-name: 'two' }
.activity-card.three { grid-name: 'three' }
.activity-card.four { grid-name: 'four' }
.activity-card.five { grid-name: 'five' }
.activity-card.six { grid-name: 'six' }

.grid-container {
   display: grid;
   grid-template-areas: 
       'one two four five'
       'one three four six';
}
```

cc @aschall777
